"""
    Thomas: a program to load the model generated by train_model.py and
    continue training it for a user-specified number of epochs.
"""

import sys

from project.id_model.train_model import *


if __name__ == "__main__":
    n_epochs = 10
    if len(sys.argv) > 1:
        try:
            n_epochs = int(sys.argv[1])
        except ValueError:
            pass

    writer2words, encoder = get_segmented_data(
        WORDS, LE_SAVE_PATH, do_gen_encoder=False)
    model, (train_generator, validation_generator,
            test_generator) = retrieve_split_dataset(writer2words, encoder)
    model.load_weights(SAVED_MODEL)

    model.compile(loss="categorical_crossentropy",
                  optimizer="adam", metrics=["accuracy", top_3_accuracy, top_5_accuracy])
    print(model.summary())

    model.fit(train_generator, validation_data=validation_generator,
              epochs=n_epochs, steps_per_epoch=250, validation_steps=50)
    
    model.evaluate(test_generator, steps=500)

    model.save(SAVED_MODEL)
