"""
    Thomas: this program just serves as glue code between the server for the app (written
    in Go) and the ID model.
"""

import json, os
from flask import Flask, request
from PIL import Image

from .model.word_segmentation import *
from .model.test_model import getAvgOutputImgs
from .model.fingerprint_test import get_fingerprint_model
from .model.train_model import SAVED_MODEL

CONFIG = "config.json"

app = Flask(__name__)
MODEL = get_fingerprint_model(SAVED_MODEL)


# Load program configuration. This should be auto-generated by setup.sh.
# Default settings will be provided if config.json is absent.
def get_config(config_path: str) -> dict:
    if os.path.exists(config_path):
        with open(config_path, "r") as config:
            return json.load(config)
    
    return { "port": 5000 }


# Return the fingerprint of an image in JSON format
@app.route("/eval", methods=["POST"])
def evaluate():
    image = Image.open(request.files["rq_image"])
    paragraph = get_paragraph_img(image)
    word_imgs = get_word_imgs(paragraph)
    fingerprint = getAvgOutputImgs(MODEL, word_imgs).tolist()
    
    return json.dumps(fingerprint)


if __name__ == "__main__":
    config = get_config(CONFIG) 
    port = config.get("port")

    if port is None or not isinstance(port, int):
        app.run(port=5000)
    else:
        app.run(port=port)
